title: Youtube
owner_name: Project MKAAT
github_username: M8tth3, kinetekenergy, BearytheGreenBear, aashrayr, trevorhuang1
github_repo: "frontend-MKAAT"
baseurl: "/frontend-MKAAT"

plugins:
- jekyll-remote-theme
future: true
